version: '3'

services:
  client:
    build:
      context: .
      args:
        GRAPHQL_ENDPOINT: http://terrella-api.com/graphql
    volumes:
      - .:/app/:rw
    environment:
      NODE_ENV: development
  api:
    image: terrella-api
  gitblit:
    image: terrella-git
