version: '3'

services:
  client:
    depends_on:
      - api
    expose:
      - 3000
    environment:
      RELAY_PLUGIN_URL: http://api:9000/graphql
      GRAPHQL_ENDPOINT: http://${API_CLIENT_HOST}/graphql
      VIRTUAL_HOST: ${CLIENT_HOST}
      VIRTUAL_PORT: 3000
  api:
    image: subspacenet/terrella-api
    depends_on:
      - db
      - gitblit
    stdin_open: true
    expose:
      - 9000
    volumes:
      - gitblit_volume:/opt/gitblit-data
    environment:
      DB_HOST: db:3306
      DB_NAME: ${DB_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASS: ${DB_USER_PASS}
      GITBLIT_PATH: /opt/gitblit-data/git/
      GITBLIT_SERVER_URL: http://gitblit:8443
      GITBLIT_CLIENT_URL: http://${GITBLIT_CLIENT_HOST}
      VIRTUAL_HOST: ${API_CLIENT_HOST}
      VIRTUAL_PORT: 9000
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASS}
  gitblit:
    image: subspacenet/terrella-git
    volumes:
      - gitblit_volume:/opt/gitblit-data
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASS: ${DB_USER_PASS}
      VIRTUAL_HOST: ${GITBLIT_CLIENT_HOST}
      VIRTUAL_PORT: 8443
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  gitblit_volume: {}
